services:

  postgres:
    image: postgres:18-bookworm
    container_name: flight-postgres
    environment:
      POSTGRES_USER: flight
      POSTGRES_PASSWORD: flight
      POSTGRES_DB: flights
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: flight-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: flight-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - kafka
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      echo 'waiting kafka...';
      cub kafka-ready -b kafka:9092 1 20;
      kafka-topics --create \
        --if-not-exists \
        --bootstrap-server kafka:9092 \
        --replication-factor 1 \
        --partitions 3 \
        --topic flight_requests;
      "

volumes:
  pgdata: