services:

  postgres:
    image: postgres:18-bookworm
    container_name: flight-postgres
    environment:
      POSTGRES_USER: flight
      POSTGRES_PASSWORD: flight
      POSTGRES_DB: flights
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: flight-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: flight-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - kafka
    entrypoint: [ "/bin/sh", "-ec" ]
    command: |
      echo "waiting for kafka..."
      for i in $(seq 1 60); do
        kafka-topics --bootstrap-server kafka:29092 --list >/dev/null 2>&1 && break
        sleep 2
      done
      
      echo "creating topic flight_requests..."
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic flight_requests --partitions 3 --replication-factor 1
      
      echo "done"

volumes:
  pgdata: