services:

  postgres:
    image: postgres:18-bookworm
    container_name: flight-postgres
    environment:
      POSTGRES_USER: flight
      POSTGRES_PASSWORD: flight
      POSTGRES_DB: flights
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U flight -d flights" ]
      interval: 5s
      timeout: 3s
      retries: 20

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: flight-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: flight-kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    container_name: flight-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: [ "/bin/bash", "-ec" ]
    command:
      - |
        echo "Kafka is healthy. Listing topics BEFORE:"
        kafka-topics --bootstrap-server kafka:9092 --list || true

        echo "Creating topic flight_requests..."
        kafka-topics --bootstrap-server kafka:9092 \
          --create --if-not-exists \
          --topic flight_requests \
          --replication-factor 1 \
          --partitions 3

        echo "Describe topic:"
        kafka-topics --bootstrap-server kafka:9092 --describe --topic flight_requests

        echo "Listing topics AFTER:"
        kafka-topics --bootstrap-server kafka:9092 --list

        echo "kafka-init done"
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flight-app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    restart: on-failure
    ports:
      - "${HTTP_PORT:-8080}:8080"
    # если хочешь, чтобы на хосте работало точно с 8080:
    # environment:
    #   HTTP_PORT: "8080"

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: flight-prometheus
    depends_on:
      - app
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.1.0
    container_name: flight-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  pgdata:
  grafana-data: