services:

  postgres:
    image: postgres:18-bookworm
    container_name: flight-postgres
    environment:
      POSTGRES_USER: flight
      POSTGRES_PASSWORD: flight
      POSTGRES_DB: flights
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: flight-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6
    container_name: flight-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    depends_on:
      - zookeeper

  kafka-init:
    image: bitnami/kafka:3.6
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      sleep 10
      kafka-topics.sh --create \
        --topic flight_requests \
        --partitions 3 \
        --replication-factor 1 \
        --if-not-exists \
        --bootstrap-server kafka:9092
      "

volumes:
  pgdata: